document.addEventListener('DOMContentLoaded', startApp);

function startApp() {
    startCloseBtn();
    createNotifications();
    autoDeleteNotification();
    startCopyBtn();
}

function autoDeleteNotification(notification = null) {
    const delay = 9000;
    if (notification) {
        setTimeout(() => notification.remove(), delay)
    } else {
        // delete generated by the page reload
        const notification = document.querySelector('.notification') || null;
        if (!notification) return;
        setTimeout(() => notification.remove(), delay)
    }
}
function startCloseBtn() {
    const container = document.querySelector('.dashboard-notifications') || null;
    if (!container) return;
    container.addEventListener('click', (e) => {
        const target = e.target;
        if (target.classList.contains('close-btn')) {
            // delete parent element  .notification
            const parent = target.parentElement.parentElement;
            if (parent.classList.contains('notification')) {
                parent.remove();
            };
        };
    })
}

function createNotifications() {
    const container = document.querySelector('.dashboard-notifications') || null;
    if (!container) return;

    window.addEventListener('create-notification', (event) => {
        const { type, text } = event.detail[0];
        const mainColor = {
            success: ' bg-green-300 text-gray-900',
            error: 'bg-red-200 text-red-600',
            info: ' bg-blue-200 text-gray-900',
            message: 'bg-gray-200 text-gray-900',
        }

        const notification = document.createElement('DIV');
        notification.className = "w-full notification relative py-3 text-sm md:text-[16px] rounded-lg my-3 mx-auto  font-bold text-center pl-3 pr-8 " + mainColor[type];

        const buttonWrapper = document.createElement('DIV');
        buttonWrapper.className = "absolute top-0 right-3 h-full  flex items-center";

        const button = document.createElement('BUTTON');
        button.className = "close-btn text-sm cursor-pointer text-gray-800 hover:text-gray-600";
        button.textContent = 'x';

        notification.append(text);
        buttonWrapper.append(button);
        notification.append(buttonWrapper);
        container.append(notification);
        autoDeleteNotification(notification);
    });
};

function startCopyBtn() {
    const vacancyList = document.querySelector('.vacancy-list') || null;
    if (!vacancyList) return;
    vacancyList.addEventListener('click', (e) => {
        const { target } = e;
        if (target.classList.contains('copy-btn') && target.nextElementSibling.classList.contains('vacancy-link')) {
            // copy href attribute to clip-board
            const linkElement = target.nextElementSibling;
            navigator.clipboard.writeText(linkElement.href);
            // .then(() => alert('copied')).catch(() => alert('failed'))
            // show small noticide under the clip
        }
    })
}
